server:
  port: 8085

spring:
  application:
    name: loyalty-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:destore}
    username: ${DB_USER:destore}
    password: ${DB_PASSWORD:destore}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
