server:
  port: 8084

spring:
  application:
    name: notification-worker
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: destore-notification
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.destore.contracts.events"

destore:
  topics:
    low-stock: low-stock
    price-changed: price-changed
